### ISSUE TITLE
Submit to CRAN

### ISSUE THREAD

**Issue by ledell** [rladies/meetupr#24]
I think we're probably ready to do our first CRAN submission!

**Comment by maelle** [comment]
I think some work is still needed, here's a list. Cc @Athanasiamo 

* [x] user-friendlier throttling cf #9 or even more hand-holding
* [x] make the switch to Markdown roxygen2, cf #83 
* [x] replace GET with RETRY if we can do that for some HTTP errors only cf #85 
* [x] #82 to make it possible to use any endpoint with our package.
* [x] #59 since it no longer works?
* [x] Fix #89 by returning empty tibbles when there are no results
* [x] Make verbose controllable by an option #94 
* [x] Ensure good test coverage and close #26
* [ ] Ensure skipping of tests with real requests for PR from forks and close #33
* [ ] Pre-build the vignette.
* [x] Fix #65 by updating the vignette.
* [x] Fix #29 
* [x] Fix #20
* [x] Fix #62
* [x] Fix #55
* [x] Fix #79
* [x] Fix #47 (add a variable with localized name)
* [ ] #21

I can spend some time on this, especially if @ledell agrees. :wink:

**Comment by drmowinckels** [comment]
meetupr is finally on CRAN! #152
